### ISSUE TITLE
CI- Auto release with Helm chart version

### ISSUE THREAD

**Issue by Piwero** [Piwero/piwhelm#15]
# TODO
- [x] #20
- [x]  Add plugin https://github.com/chartmuseum/helm-push
- [x] Add labels
- [x] Github action
- [x] Setup semantic releases GH action
- [ ] Semantic release tag triggers helm chart version
